spring.application.name=sebastian
server.port=8089

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true
management.endpoints.web.exposure.include=*
eureka.client.healthcheck.enabled=true

custom.greeting=Hola desde Config Server para sebastian
